name: armoyu
description: Resmi ARMOYU Flutter projesidir.
publish_to: "none"
version: 1.0.16+100

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  cached_network_image: ^3.3.0
  crypto: ^3.0.3
  provider: ^6.0.5
  theme_provider: ^0.6.0
  # flutter_barcode_scanner: ^2.0.0
  image_picker: ^1.0.7
  image_cropper: ^8.0.1
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  device_info_plus: ^10.0.1
  package_info_plus: ^8.0.1
  connectivity_plus: ^6.0.1
  onesignal_flutter: ^5.2.0
  detectable_text_field: ^3.0.2
  flutter_hooks: ^0.20.5
  carousel_slider: ^5.0.0
  like_button: ^2.0.5
  badges: ^3.1.2
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.5
  photo_manager: ^3.6.1
  photo_view: ^0.15.0
  camera: ^0.11.0+1
  video_player: ^2.8.3
  chewie: ^1.7.5
  wakelock_plus: ^1.1.6
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  permission_handler: ^11.3.0
  # just_audio: ^0.9.36
  audioplayers: ^6.1.0

  flutter_mentions: ^2.0.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.1
  easy_localization: ^3.0.5
  flutter_multi_formatter: ^2.12.8
  font_awesome_flutter: ^10.7.0
  pinch_zoom: ^2.0.0
  qr_flutter: ^4.1.0
  get: ^4.6.6
  get_storage: ^2.1.1

  share_plus: ^10.1.2
  marquee: ^2.3.0
  socket_io_client: ^3.0.0
  country_flags: ^3.0.0

  armoyu_services: ^1.0.0+55
  armoyu_widgets: ^1.0.0+66

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
